version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: /Users/vladimirocheret/Code/Microservices/go-micro/broker-service/cmd/api/broker-service.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1